#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
#
# T-16.6a — live AT-SPI dump and keyboard-only walkthrough.
#
# Produces:
#   * docs/captures/t16-a11y-atspi.txt  the live AT-SPI tree of the first-party
#                                      apps plus the keyboard-only walkthrough
#                                      transcript (focus moves read back from
#                                      AT-SPI, pane selection in Settings)
#   * docs/captures/t16-a11y-desktop.png the nested desktop still (live visual
#                                      check)
#
# It launches the nested `make demo` session twice with
# `QT_LINUX_ACCESSIBILITY_ALWAYS_ON=1` (so Qt registers on the host AT-SPI
# accessibility bus) and a synthetic-input socket (so the walkthrough is
# keyboard-only and needs no pointer):
#   1. Settings (the demo's default Qt app),
#   2. Files (`DF_DEMO_QT_APP`).
# The shell chrome is offscreen and is NOT on the accessibility bus (see ADR
# 0154); its AT-SPI roles are asserted per component in `make qml-test` and its
# global keyboard flows in `keyboard_only_walkthrough_dispatches_every_system_binding`.
#
# Requires: a host Wayland session, python3 with `pyatspi` and Pillow, the
# built tree (`make build`). Not part of `make e2e`.
set -euo pipefail

root="$(cd "$(dirname "$0")/.." && pwd)"
cd "$root"
export LD_LIBRARY_PATH="$HOME/.local/df-toolchain/usr/lib64${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"

OUTDIR="${OUTDIR:-docs/captures}"
SETTLE="${SETTLE:-14}"
mkdir -p "$OUTDIR" /tmp/opencode

DEMO="${DEMO:-target/debug/dragonfruit}"
[ -x "$DEMO" ] || { echo "t16-a11y-audit: $DEMO missing — run make build"; exit 1; }
command -v python3 >/dev/null || { echo "t16-a11y-audit: python3 missing"; exit 1; }
python3 -c "import pyatspi" 2>/dev/null || {
    echo "t16-a11y-audit: python3 pyatspi missing (install at-spi2-core / python3-pyatspi)"; exit 1; }
[ -n "${WAYLAND_DISPLAY:-}" ] || { echo "t16-a11y-audit: no host Wayland session"; exit 1; }

TRANSCRIPT="$OUTDIR/t16-a11y-atspi.txt"
: >"$TRANSCRIPT"
echo "# T-16.6a live AT-SPI audit" >>"$TRANSCRIPT"
echo "# generated by scripts/t16-a11y-audit.sh" >>"$TRANSCRIPT"
echo >>"$TRANSCRIPT"

overall=0

run_pass() {
    local app_name="$1" app_bin="$2" socket="$3" title="$4"
    local synth="${XDG_RUNTIME_DIR:?}/$socket.synth"
    local log="/tmp/opencode/$socket.log"
    rm -f "$synth" "$log"

    echo "t16-a11y-audit: pass '$title' ($app_name)"
    if [ -n "$app_bin" ]; then
        DF_DEMO_QT_APP="$app_bin" \
        QT_LINUX_ACCESSIBILITY_ALWAYS_ON=1 \
        DRAGONFRUIT_SYNTHETIC_INPUT="$synth" \
            setsid "$DEMO" dev --demo --socket-name "$socket" >"$log" 2>&1 &
    else
        QT_LINUX_ACCESSIBILITY_ALWAYS_ON=1 \
        DRAGONFRUIT_SYNTHETIC_INPUT="$synth" \
            setsid "$DEMO" dev --demo --socket-name "$socket" >"$log" 2>&1 &
    fi
    local pgid=$!
    # shellcheck disable=SC2064
    trap "kill -TERM -$pgid 2>/dev/null || true; sleep 1; kill -KILL -$pgid 2>/dev/null || true; rm -f '$synth'" RETURN

    for _ in $(seq 1 600); do [ -e "$synth" ] && break; sleep 0.1; done
    if [ ! -e "$synth" ]; then
        echo "t16-a11y-audit: no synthetic socket for '$title'" | tee -a "$TRANSCRIPT"
        tail -20 "$log" || true
        overall=1
        return
    fi
    sleep "$SETTLE"

    if python3 scripts/t16-a11y-audit.py "$synth" "$app_name" >>"$TRANSCRIPT"; then
        echo "t16-a11y-audit: '$title' PASS"
    else
        echo "t16-a11y-audit: '$title' FAIL"
        overall=1
    fi
    echo >>"$TRANSCRIPT"

    # Live still: the Settings pass is the representative desktop.
    if [ "$app_name" = "dragonfruit-settings" ]; then
        local raw="/tmp/opencode/t16-a11y-desktop-raw.png"
        spectacle -b -n -a -o "$raw" >/dev/null 2>&1 \
            || spectacle -b -n -f -o "$raw" >/dev/null 2>&1 || true
        if [ -f "$raw" ]; then
            python3 - "$raw" "$OUTDIR/t16-a11y-desktop.png" <<'PY'
import sys
from PIL import Image
im = Image.open(sys.argv[1]).convert("RGB")
im.save(sys.argv[2])
print("saved", sys.argv[2], im.size)
PY
        fi
    fi

    kill -TERM -"$pgid" 2>/dev/null || true
    sleep 1
    kill -KILL -"$pgid" 2>/dev/null || true
    trap - RETURN
    rm -f "$synth"
}

run_pass "dragonfruit-settings" "" "dragonfruit-t16-a11y-settings" "Settings"
run_pass "dragonfruit-files" "build/apps/files/dragonfruit-files" \
    "dragonfruit-t16-a11y-files" "Files"

echo "t16-a11y-audit: transcript -> $TRANSCRIPT"
[ "$overall" -eq 0 ] && echo "t16-a11y-audit: PASS" || echo "t16-a11y-audit: FAIL"
exit "$overall"